name: flutter_bounceable
description: A simple, interactive and customizable on-tap bounce animation that can be wrapped on any widgets that you like.
version: 1.0.3
repository: https://github.com/MingSern/flutter_bounceable
issue_tracker: https://github.com/MingSern/flutter_bounceable/issues

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:
